# Generated by Django 3.1.4 on 2020-12-19 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('protestId', '0002_protest_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('protest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protestId.protest')),
            ],
        ),
    ]
