# Generated by Django 3.1.4 on 2020-12-19 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('participants', models.IntegerField(blank=True, default=0, null=True)),
                ('upiId', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
