# Generated by Django 3.1.3 on 2020-12-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protestId', '0003_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
